### ISSUE TITLE
TypeError: Cannot redefine property When back to same Component by VueRoute

### ISSUE THREAD

**Issue by wowissu** [kaorun343/vue-property-decorator#274]
https://github.com/kaorun343/vue-property-decorator/blob/9aecbd28c53927494f51202c3682632bbeffb6ad/src/vue-property-decorator.ts#L106

vue-property-decorator@8.3.0

I have the problem when using the ProvideReactive with VueRouter
always get the "TypeError: Cannot redefine property:" when back to the same Component at Second  time

I am very sure the component is Destoryed at first time and I am not using the \<keeplive /> or something else like that 

maybe use the "hasOwnProperty" before defineProperty  ? 
```js
if (
  !rv[reactiveInjectKey].hasOwnProperty(provide.managedReactive[i])
) {
  Object.defineProperty(
    rv[reactiveInjectKey],
    provide.managedReactive[i],
    {
      enumerable: true,
      get: function() {
        return _this[i];
      },
    },
  );
}
```

**Comment by anoff** [comment]
Same here, configuration

```
export default class List extends Vue {
  @ProvideReactive() newChangeBlip: Blip
```

**Comment by CeceWall** [comment]
@anoff when i downgrade to v8.2.1, this issue was fixed, but my @ProvideReactive property in mixin file didn't work any more.

**Comment by anoff** [comment]
@CeceWall I am only using `ProvideReactive` in a component directly and in my case it still seems to work. Do you depend on a feature that was introduced with `8.3.0`

**Comment by Cyclodex** [comment]
Still broken in 8.4.x

Same issue here, however I don't get any "errors" it just doesn't work.
I use the route re-rendering right now, maybe this is why I dont get an error... But the Provide/Inject feature completely stops to work then.

`<router-view :key="$route.fullPath"`

All works fine with 8.2.2 for me.

**Comment by surajsudhera** [comment]
> Still broken in 8.4.x
> 
> Same issue here, however I don't get any "errors" it just doesn't work.
> I use the route re-rendering right now, maybe this is why I dont get an error... But the Provide/Inject feature completely stops to work then.
> 
> `<router-view :key="$route.fullPath"`
> 
> All works fine with 8.2.2 for me.

still broken in 9.0.0 :( 

but 8.2.2 works fine

**Comment by wowissu** [comment]
> > Still broken in 8.4.x
> > Same issue here, however I don't get any "errors" it just doesn't work.
> > I use the route re-rendering right now, maybe this is why I dont get an error... But the Provide/Inject feature completely stops to work then.
> > `<router-view :key="$route.fullPath"`
> > All works fine with 8.2.2 for me.
> 
> still broken in 9.0.0 :(
> 
> but 8.2.2 works fine

[https://github.com/kaorun343/vue-property-decorator/issues/277#issuecomment-558594655](url)

Here is the solution.
set `inject: []` in Component options
